### ISSUE TITLE
UnhandledPromiseRejectionWarning while downloading

### ISSUE THREAD

**Issue by sultanmomynov** [sultanmomynov/telegram-bot#1]
(node:23189) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /run/media/sultan/4637634824FDDD04/Projects/telegram-bot/node_modules/youtube-dl/bin/youtube-dl -x --audio-format mp3 -o ./tmp/%(id)s.%(ext)s http://www.youtube.com/watch?v=aaa2_GLibYI
    at makeError (/run/media/sultan/4637634824FDDD04/Projects/telegram-bot/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/run/media/sultan/4637634824FDDD04/Projects/telegram-bot/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sultanmomynov** [comment]
Not reproduced
